name: pyBasket
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9 # pytorch only support this for now
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - loguru
  - jupyterlab
  - ipywidgets
  - pymc
  - arviz
  - pytorch
  - torchvision
  - mkl < 2022 # https://stackoverflow.com/questions/70830755/intel-mkl-fatal-error-this-system-does-not-meet-the-minimum-requirements-for-us/71640311#71640311
  - flake8
  - autopep8
  - pytest
  - pytest-cov
  - pip
  - pip:
    - twine
    - build
    - mkdocs
    - mkdocstrings
