DEFAULT_NUM_CHAINS = None # let pymc decide
DEFAULT_EFFICACY_CUTOFF = 0.90
DEFAULT_FUTILITY_CUTOFF = 0.05
DEFAULT_EARLY_FUTILITY_STOP = False
DEFAULT_EARLY_EFFICACY_STOP = False

GROUP_STATUS_OPEN = 'OPEN'
GROUP_STATUS_EARLY_STOP_FUTILE = 'EARLY_STOP_FUTILE'
GROUP_STATUS_EARLY_STOP_EFFECTIVE = 'EARLY_STOP_EFFECTIVE'
GROUP_STATUS_COMPLETED_INEFFECTIVE = 'COMPLETED_INEFFECTIVE'
GROUP_STATUS_COMPLETED_EFFECTIVE = 'COMPLETED_EFFECTIVE'